[features]
seeds = true
skip-lint = false
[programs.devnet]
coinflip_new = "26Kzq7jgtst8BfT6oSWCxR1Di8JNBpZs8sytTgq1tik3"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/Users/drou/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
